version: '3.7'

networks:
  docker_network:
    name: ${NETWORK}

services:

  adminer:
    image: adminer:4.8.0-standalone
    restart: always
    container_name: adminer
    networks:
      docker_network:
    environment:
      ADMINER_PLUGINS: ${ADMINER_PLUGINS}
      ADMINER_DESIGN: ${ADMINER_DESIGN}
    ports:
      - ${ADMINER_PORT}:8080

  postgres:
    image: postgres:13.1
    restart: always
    container_name: postgres
    networks:
      docker_network:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    image: redis:6.2.7
    container_name: redis
    networks:
      docker_network:
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ${REDIS_VOLUME}:/bitnami/redis/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"

  mongo:
    image: mongo:6.0-focal
    restart: always
    container_name: mongo
    networks:
      docker_network:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${MONGO_VOLUME}:/data/db
      - ./mongo/mongodb.conf:/etc/mongodb.conf
    ports:
      - "${MONGO_PORT}:27017-27019"

  mongo-express:
    image: mongo-express:0.49.0
    restart: always
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    networks:
      docker_network:
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
   
  nginx:
    image: nginx:stable-alpine
    restart: always
    container_name: nginx
    networks:
      docker_network:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"


